const scenarios = [];
const host = 'http://localhost:9090';
const urls = [
	'/zeit-online/article/01',
	'/zeit-online/article/02',
	'/zeit-online/article/administratives',
	'/zeit-online/article/advertorial',
	'/zeit-online/article/advertorial-onepage',
	'/zeit-online/article/afp',
	'/zeit-online/article/all-blocks',
	'/zeit-online/article/alte-eilmeldung',
	'/zeit-online/article/alte-archivtext',
	'/zeit-online/article/amp',
	'/zeit-online/article/amp-invalid',
	'/zeit-online/article/amp-ohne-autor',
	'/zeit-online/article/angebot',
	'/zeit-online/article/article_with_broken_image_asset',
	'/zeit-online/article/article_with_expired_image',
	'/zeit-online/article/authorbox',
	'/zeit-online/article/banner_content_no',
	'/zeit-online/article/copyrights',
	'/zeit-online/article/dpa',
	'/zeit-online/article/dpa-image',
	'/zeit-online/article/dpa-table',
	'/zeit-online/article/eilmeldungsartikel',
	'/zeit-online/article/embed-header-image',
	'/zeit-online/article/embed-header-quiz',
	'/zeit-online/article/embed-header-raw',
	'/zeit-online/article/embed-header-video',
	'/zeit-online/article/feedback',
	'/zeit-online/article/feedback-in-article',
	'/zeit-online/article/fischer',
	'/zeit-online/article/image-column-width',
	'/zeit-online/article/infoboxartikel',
	'/zeit-online/article/infografix',
	'/zeit-online/article/infographic',
	'/zeit-online/article/inline-gallery',
	'/zeit-online/article/intext-disabled',
	'/zeit-online/article/jquery-local-scope',
	'/zeit-online/article/liveblog',
	'/zeit-online/article/liveblog-collapse',
	'/zeit-online/article/liveblog-no-collapse',
	'/zeit-online/article/liveblog3',
	'/zeit-online/article/liveblog3-solo-theme',
	'/zeit-online/article/missing-contenttype',
	'/zeit-online/article/narrow',
	'/zeit-online/article/paginated',
	'/zeit-online/article/podcast',
	'/zeit-online/article/podcast-header',
	'/zeit-online/article/podcast-header-serie',
	'/zeit-online/article/portraitbox',
	'/zeit-online/article/portraitbox_invalid',
	'/zeit-online/article/quiz',
	'/zeit-online/article/quotes',
	'/zeit-online/article/raw_code',
	'/zeit-online/article/serie-eilmeldung',
	'/zeit-online/article/serie-liveblog',
	'/zeit-online/article/simple',
	'/zeit-online/article/simple-ligatus-disabled',
	'/zeit-online/article/simple-ligatus-donotindex',
	'/zeit-online/article/simple-merian-nofollow',
	'/zeit-online/article/simple-multipage',
	'/zeit-online/article/simple-nextread',
	'/zeit-online/article/simple-nextread-column',
	'/zeit-online/article/simple-nextread-expired-image',
	'/zeit-online/article/simple-nextread-liveblog',
	'/zeit-online/article/simple-nextread-register',
	'/zeit-online/article/simple-nextread-taglogo',
	'/zeit-online/article/simple-nextread-zett',
	'/zeit-online/article/simple-nextread-zmo',
	'/zeit-online/article/simple-nextread-zplus',
	'/zeit-online/article/simple-verlagsnextread',
	'/zeit-online/article/tagesspiegel',
	'/zeit-online/article/tags',
	'/zeit-online/article/video',
	'/zeit-online/article/video-ads',
	'/zeit-online/article/video-expired',
	'/zeit-online/article/volumeteaser',
	'/zeit-online/article/volumeteaser-fallback',
	'/zeit-online/article/webtrekk-test',
	'/zeit-online/article/zeit',
	'/zeit-online/article/zeit-geld-print-insert',
	'/zeit-online/article/zplus-nocover',
	'/zeit-online/article/zplus-novolume',
	'/zeit-online/article/zplus-short-summary',
	'/zeit-online/article/zplus-zeit',
	'/zeit-online/article/zplus-zeit-free',
	'/zeit-online/article/zplus-zeit-register',
	'/zeit-online/article/zplus-zon',
	'/zeit-online/article/zplus-zon-register',
];

urls.forEach(url => {
	scenarios.push({
		label: url,
		cookiePath: '',
		url: `${host}${url}`,
		referenceUrl: '',
		readyEvent: '',
		readySelector: '',
		delay: 100,
		hideSelectors: [],
		removeSelectors: ['#pDebug'],
		hoverSelector: '',
		clickSelector: '',
		postInteractionWait: '',
		selectors: ['html'],
		selectorExpansion: true,
		misMatchThreshold: 0.1,
		requireSameDimensions: true,
	});
});

module.exports = scenarios;
