let scenarios = []
const urls = [
    'http://localhost:9090/zeit-online/article/01',
    'http://localhost:9090/zeit-online/article/02',
    'http://localhost:9090/zeit-online/article/administratives',
    'http://localhost:9090/zeit-online/article/advertorial',
    'http://localhost:9090/zeit-online/article/advertorial-onepage',
    'http://localhost:9090/zeit-online/article/afp',
    'http://localhost:9090/zeit-online/article/all-blocks',
    'http://localhost:9090/zeit-online/article/alte-eilmeldung',
    'http://localhost:9090/zeit-online/article/alte-archivtext',
    'http://localhost:9090/zeit-online/article/amp',
    'http://localhost:9090/zeit-online/article/amp-invalid',
    'http://localhost:9090/zeit-online/article/amp-ohne-autor',
    'http://localhost:9090/zeit-online/article/angebot',
    'http://localhost:9090/zeit-online/article/article_with_broken_image_asset',
    'http://localhost:9090/zeit-online/article/article_with_expired_image',
    'http://localhost:9090/zeit-online/article/authorbox',
    'http://localhost:9090/zeit-online/article/banner_content_no',
    'http://localhost:9090/zeit-online/article/cardstack',
    'http://localhost:9090/zeit-online/article/copyrights',
    'http://localhost:9090/zeit-online/article/dpa',
    'http://localhost:9090/zeit-online/article/dpa-image',
    'http://localhost:9090/zeit-online/article/dpa-table',
    'http://localhost:9090/zeit-online/article/eilmeldungsartikel',
    'http://localhost:9090/zeit-online/article/embed-header-cardstack',
    'http://localhost:9090/zeit-online/article/embed-header-image',
    'http://localhost:9090/zeit-online/article/embed-header-quiz',
    'http://localhost:9090/zeit-online/article/embed-header-raw',
    'http://localhost:9090/zeit-online/article/embed-header-video',
    'http://localhost:9090/zeit-online/article/feedback',
    'http://localhost:9090/zeit-online/article/feedback-in-article',
    'http://localhost:9090/zeit-online/article/fischer',
    'http://localhost:9090/zeit-online/article/image-column-width',
    'http://localhost:9090/zeit-online/article/info-bonobo',
    'http://localhost:9090/zeit-online/article/infoboxartikel',
    'http://localhost:9090/zeit-online/article/infografix',
    'http://localhost:9090/zeit-online/article/infographic',
    'http://localhost:9090/zeit-online/article/inline-gallery',
    'http://localhost:9090/zeit-online/article/intext-disabled',
    'http://localhost:9090/zeit-online/article/jquery-local-scope',
    'http://localhost:9090/zeit-online/article/liveblog',
    'http://localhost:9090/zeit-online/article/liveblog-collapse',
    'http://localhost:9090/zeit-online/article/liveblog-no-collapse',
    'http://localhost:9090/zeit-online/article/liveblog3',
    'http://localhost:9090/zeit-online/article/liveblog3-solo-theme',
    'http://localhost:9090/zeit-online/article/missing-contenttype',
    'http://localhost:9090/zeit-online/article/narrow',
    'http://localhost:9090/zeit-online/article/paginated',
    'http://localhost:9090/zeit-online/article/podcast',
    'http://localhost:9090/zeit-online/article/podcast-header',
    'http://localhost:9090/zeit-online/article/podcast-header-serie',
    'http://localhost:9090/zeit-online/article/portraitbox_inline',
    'http://localhost:9090/zeit-online/article/portraitbox_invalid',
    'http://localhost:9090/zeit-online/article/quiz',
    'http://localhost:9090/zeit-online/article/quotes',
    'http://localhost:9090/zeit-online/article/raw_code',
    'http://localhost:9090/zeit-online/article/serie-cardstack',
    'http://localhost:9090/zeit-online/article/serie-eilmeldung',
    'http://localhost:9090/zeit-online/article/serie-liveblog',
    'http://localhost:9090/zeit-online/article/simple',
    'http://localhost:9090/zeit-online/article/simple-ligatus-disabled',
    'http://localhost:9090/zeit-online/article/simple-ligatus-donotindex',
    'http://localhost:9090/zeit-online/article/simple-merian-nofollow',
    'http://localhost:9090/zeit-online/article/simple-multipage',
    'http://localhost:9090/zeit-online/article/simple-nextread',
    'http://localhost:9090/zeit-online/article/simple-nextread-column',
    'http://localhost:9090/zeit-online/article/simple-nextread-expired-image',
    'http://localhost:9090/zeit-online/article/simple-nextread-liveblog',
    'http://localhost:9090/zeit-online/article/simple-nextread-register',
    'http://localhost:9090/zeit-online/article/simple-nextread-taglogo',
    'http://localhost:9090/zeit-online/article/simple-nextread-zco',
    'http://localhost:9090/zeit-online/article/simple-nextread-zett',
    'http://localhost:9090/zeit-online/article/simple-nextread-zmo',
    'http://localhost:9090/zeit-online/article/simple-nextread-zplus',
    'http://localhost:9090/zeit-online/article/simple-verlagsnextread',
    'http://localhost:9090/zeit-online/article/tagesspiegel',
    'http://localhost:9090/zeit-online/article/tags',
    'http://localhost:9090/zeit-online/article/video',
    'http://localhost:9090/zeit-online/article/video-ads',
    'http://localhost:9090/zeit-online/article/video-expired',
    'http://localhost:9090/zeit-online/article/volumeteaser',
    'http://localhost:9090/zeit-online/article/volumeteaser-fallback',
    'http://localhost:9090/zeit-online/article/webtrekk-test',
    'http://localhost:9090/zeit-online/article/zeit',
    'http://localhost:9090/zeit-online/article/zeit-geld-print-insert',
    'http://localhost:9090/zeit-online/article/zplus-nocover',
    'http://localhost:9090/zeit-online/article/zplus-novolume',
    'http://localhost:9090/zeit-online/article/zplus-short-summary',
    'http://localhost:9090/zeit-online/article/zplus-zeit',
    'http://localhost:9090/zeit-online/article/zplus-zeit-free',
    'http://localhost:9090/zeit-online/article/zplus-zeit-register',
    'http://localhost:9090/zeit-online/article/zplus-zon',
    'http://localhost:9090/zeit-online/article/zplus-zon-register',
];

urls.forEach(url => {
  scenarios.push({
    'label': url.replace('http://localhost:9090/', '').replace(/\//g, '_'),
    'cookiePath': '',
    'url': url,
    'referenceUrl': '',
    'readyEvent': '',
    'readySelector': '',
    'delay': 100,
    'hideSelectors': [],
    'removeSelectors': [
      '#pDebug'
    ],
    'hoverSelector': '',
    'clickSelector': '',
    'postInteractionWait': '',
    'selectors': ['html'],
    'selectorExpansion': true,
    'misMatchThreshold': 0.1,
    'requireSameDimensions': true
  });
});

module.exports = scenarios;
