var data = [
    {
        'id': 958034,
        'competition': 'fb_mwm',
        'season': 2018,
        'matchday': 1,
        'date': new Date( new Date().getTime() - ( 1000 * 60 * 47 ) ),
        'today': true,
        'kickoff': new Date( new Date().getTime() - ( 1000 * 60 * 47 ) ),
        'status': 'LIVE',
        'period': 1,
        'running': true,
        'home_code': 'FRA',
        'away_code': 'AUS',
        'home_name': 'Frankreich',
        'away_name': 'Australien',
        'home_score': null,
        'away_score': 1
    },
    {
        'id': 958041,
        'competition': 'fb_mwm',
        'season': 2018,
        'matchday': 1,
        'date': new Date( new Date().getTime() - ( 1000 * 60 * 43 ) ),
        'today': true,
        'kickoff': new Date( new Date().getTime() - ( 1000 * 60 * 43 ) ),
        'status': 'LIVE',
        'running': true,
        'period': 2,
        'home_id': 't632',
        'away_id': 't503',
        'home_code': 'ARG',
        'away_code': 'ISL',
        'home_name': 'Argentinien',
        'away_name': 'Island',
        'home_score': 2,
        'away_score': 1
    },
    {
        'id': 958035,
        'competition': 'fb_mwm',
        'season': 2018,
        'matchday': 1,
        'date': new Date( new Date().getTime() + ( 1000 * 60 * 120 ) ),
        'today': true,
        'kickoff': new Date( new Date().getTime() + ( 1000 * 60 * 120 ) ),
        'status': 'FULL',
        'running': false,
        'comment': null,
        'home_id': 't834',
        'away_id': 't369',
        'home_code': 'PER',
        'away_code': 'DNK',
        'home_name': 'Peru',
        'away_name': 'Dänemark',
        'home_likes': 0,
        'away_likes': 0,
        'home_score': 2,
        'away_score': 4
    },
    {
        'id': 958040,
        'competition': 'fb_mwm',
        'season': 2018,
        'matchday': 1,
        'date': new Date( new Date().getTime() + ( 1000 * 60 * 120 ) ),
        'today': false,
        'kickoff': new Date( new Date().getTime() + ( 1000 * 60 * 120 ) ),
        'status': 'PRE-MATCH',
        'running': false,
        'comment': null,
        'home_id': 't535',
        'away_id': 't1216',
        'home_code': 'HRV',
        'away_code': 'NGA',
        'home_name': 'Kroatien',
        'away_name': 'Nigeria',
        'home_likes': 0,
        'away_likes': 0,
        'home_score': null,
        'away_score': null
    }
];

module.exports = data;
