var data = [
    {
        'id': 958034,
        'competition': 'fb_mwm',
        'season': 2018,
        'matchday': 1,
        'date': new Date( null, null, null, 12, 0, 0, 0 ),
        'today': true,
        'kickoff': new Date( null, null, null, 13, 0, 0, 0 ),
        'status': 'LIVE',
        'running': true,
        'home_code': 'FRA',
        'away_code': 'AUS',
        'home_name': 'Frankreich',
        'away_name': 'Australien',
        'home_score': 1,
        'away_score': 3
    },
    {
        'id': 958041,
        'competition': 'fb_mwm',
        'season': 2018,
        'matchday': 1,
        'date': new Date( null, null, null, 12, 30, 0, 0 ),
        'today': true,
        'kickoff': new Date( null, null, null, 12, 30, 0, 0 ),
        'status': 'HALF-EXTRATIME',
        'running': true,
        'home_id': 't632',
        'away_id': 't503',
        'home_code': 'ARG',
        'away_code': 'ISL',
        'home_name': 'Argentinien',
        'away_name': 'Island',
        'home_score': 1,
        'away_score': null
    },
    {
        'id': 958035,
        'competition': 'fb_mwm',
        'season': 2018,
        'matchday': 1,
        'date': '2018-06-16T18:00:00+02:00',
        'today': false,
        'kickoff': null,
        'status': 'PRE-MATCH',
        'running': false,
        'comment': null,
        'home_id': 't834',
        'away_id': 't369',
        'home_code': 'PER',
        'away_code': 'DNK',
        'home_name': 'Peru',
        'away_name': 'Dänemark',
        'home_likes': 0,
        'away_likes': 0,
        'home_score': null,
        'away_score': null
    },
    {
        'id': 958040,
        'competition': 'fb_mwm',
        'season': 2018,
        'matchday': 1,
        'date': '2018-06-16T21:00:00+02:00',
        'today': false,
        'kickoff': null,
        'status': 'PRE-MATCH',
        'running': false,
        'comment': null,
        'home_id': 't535',
        'away_id': 't1216',
        'home_code': 'HRV',
        'away_code': 'NGA',
        'home_name': 'Kroatien',
        'away_name': 'Nigeria',
        'home_likes': 0,
        'away_likes': 0,
        'home_score': null,
        'away_score': null
    }
];

module.exports = data;
